# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-002.html
http://web-platform.test:8000/css/css-anchor-position/anchor-center-no-default.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-overflow-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-overflow-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-overflow-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-overflow-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-overflow-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-safe-rtl.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-safe.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-scroll-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-scroll-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-scroll-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-center-visibility-change.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-css-zoom.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-fieldset-001.html
http://web-platform.test:8000/css/css-anchor-position/anchor-fixed-pos-descendant.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-function-chain-pseudo-elements.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-in-css-min-max-function.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-name-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-name-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-name-007.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-name-dynamic-reflow-root.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-name-multicol-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-name-multicol-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-circular.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-dynamic-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-grid-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-grid-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-inline-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-inline-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-inline-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-inline-007.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-007.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-008.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-011.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-012.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-013.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-014.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-015.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-016.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-017.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-colspan-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-fixed-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-multicol-nested-001.html
http://web-platform.test:8000/css/css-anchor-position/anchor-position-non-anchored-fallback.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-top-layer-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-top-layer-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-top-layer-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-top-layer-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-top-layer-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-position-top-layer-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scope-scroll.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-chained-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-chained-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-chained-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-chained-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-chained-fallback.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-composited-scrolling-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-composited-scrolling-paint-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-fixedpos-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-fixedpos-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-fixedpos-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-fixedpos.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-implicit-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-implicit-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-nested.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-overflow-hidden.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-position-try-012.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-position-try-015.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-scrollable-anchor.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-to-sticky-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-to-sticky-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-to-sticky-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-to-sticky-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-update-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-update-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-update-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-update-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-update-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-update-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-update-007.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-update-008.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-update-009.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-update-010.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-vlr.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-scroll-vrl.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-size-css-zoom.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchor-size-function-chain-pseudo-elements.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchored-c-v-hidden.html
http://web-platform.test:8000/css/css-anchor-position/anchored-transition-display-none-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/anchored-transition-display-none-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/auto-margins-position-area.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/container-queries/anchored-fallback-color-change.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/container-queries/anchored-fallback-style-containment.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/grid-position-area-basic.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/inherit-height-from-fallback.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/no-anchor-anchor-center.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-anchor-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-anchor-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-anchor-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-anchor-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-anchor-dynamic-unset-raf-visibility-hidden.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-anchor-dynamic-unset-visibility-hidden.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-anchor-normal-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-anchor-target-with-children.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-abs-inline-container.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-alignment-inset-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-anchor-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-anchor-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-chain-pseudo-elements.html
http://web-platform.test:8000/css/css-anchor-position/position-area-change.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-inline-container.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-inset-one-side-auto.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-justify-self-safe-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-no-default-anchor.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-overflow-icb-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-overflow-icb-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-overflow-icb-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-overflow-icb-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-percents-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-pseudo-element-implicit-anchor-dynamic.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-pseudo-element-implicit-anchor.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-scroll-adjust.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-scrolling-004.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-area-visibility-change.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-try-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-try-fallbacks-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-try-fallbacks-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-try-fallbacks-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-try-order-logical.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-try-switch-from-fixed-anchor.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-try-switch-to-fixed-anchor.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-try-tree-scoped-pseudo.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-add-no-overflow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-valid.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-after-scroll-in-document.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-after-scroll-in.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-after-scroll-out.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-both-position-fixed.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-chained-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-chained-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-chained-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-chained-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-change-anchor.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-change-css-visibility.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-clip.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-css-visibility.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-dynamic-anchor-toggle.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-in-overflow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-non-intervening-container.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-position-fixed.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-stacked-child.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-stacked-child.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible-with-position.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-anchors-visible.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-initial.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-no-overflow-nested.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-no-overflow-scroll-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-no-overflow-scroll.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-no-overflow-stacked-child.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-no-overflow-without-anchor.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-no-overflow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-remove-anchors-visible.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/position-visibility-remove-no-overflow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/pseudo-element-implicit-anchor-center.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/pseudo-element-implicit-anchor.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/pseudo-element-with-slotted-anchor.html
# [auto-fail:TC_CRASH] http://web-platform.test:8000/css/css-anchor-position/scroll-to-anchored-fixed-000.html
http://web-platform.test:8000/css/css-anchor-position/scroll-to-anchored-fixed-001.html
http://web-platform.test:8000/css/css-anchor-position/scroll-to-anchored-fixed-002.html
# http://web-platform.test:8000/css/css-anchor-position/scroll-to-anchored-fixed-003.html
# http://web-platform.test:8000/css/css-anchor-position/scroll-to-anchored-fixed-004.html
http://web-platform.test:8000/css/css-anchor-position/scroll-to-anchored-fixed-005.html
http://web-platform.test:8000/css/css-anchor-position/scroll-to-anchored-fixed-006.html
http://web-platform.test:8000/css/css-anchor-position/sticky-anchor-position-invalid.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/transform-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/transform-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/transform-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/transform-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/transform-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/transform-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/transform-007.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/transform-008.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/transform-009.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/under-invalidation.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-anchor-position/vertical-aligned-table-cell.html
